### PR TITLE
Update SmartBlogLink.php

### PR DESCRIPTION
**Pull request by PrestaSafe**
fix for ssl url image on category list.

### CODE REVIEW

**Comment by smartdatasoft** [comment]
hello, did you check it work fine. with or without ssl site.

**Comment by sirius82** [comment]
Hello, I tried to add this code (Smartblog 3.0.0, PS 1.7.5.2) but the problem is not solved  :  after to have enabled SSL, all featured images of blog are no more displayed (src {unknown}). Even if I re-disable SSL.
Do you have an idea ? Thanks

**Comment by sirius82** [comment]
Finally, it works fine ! thanks !

**Review by Enumbin — APPROVED** [review]

**Comment by Enumbin** [comment]
Thank You For Your Pull Request

**Pull request merged**
