### PR TITLE
Meta Title Issue Fixed

### PR DESCRIPTION
**Pull request by Enumbin**

### CODE REVIEW

**Comment by SharakPL** [comment]
I think you need to start using PHP Code Sniffer and at least PSR-2 standards because your code is quite messy. Now you've started using tabs instead of spaces and they're 8 spaces long. Standard indentation in PHP is 4 spaces, no tabs.
Vim isn't the best for this 😏

**Comment by Enumbin** [comment]
Thank you so much @SharakPL. We are working on it. As soon as we fix all the issues we will surely format it. Actually we use PhpCodsniffer in VSCode but I think that does not help much. Can you suggest a tutorial or anything to do it? 

For your information you can check out other modules at https://classydevs.com/ 

Thank you so much brother.

**Comment by SharakPL** [comment]
For VSCode I recommend [PHP Intelephense](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client) and set it as defualt formatter. <kbd>CTRL + ,</kbd> in VSCode to open settings.json (switch to json mode in top right corner if you're in UI mode) and add this:

```
  "[php]": {
    "editor.tabSize": 4,
    "editor.insertSpaces": true,
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "bmewburn.vscode-intelephense-client"
  },
```

It will auto format your code and underline mistakes that can only be fixed manually.

PHP Code Sniffer (I'm using [this extension](https://marketplace.visualstudio.com/items?itemName=wongjn.php-sniffer)) adds more linting, but it requires phpcs [installed](https://github.com/squizlabs/PHP_CodeSniffer) on your system with composer to work so

```
composer global require "squizlabs/php_codesniffer=*"
```

and add this to settings.json:

```
  "php.suggest.basic": false,
  "php.validate.enable": false,
  "phpSniffer.autoDetect": true,
  "phpSniffer.onTypeDelay": 500,
  "phpSniffer.run": "onType",
  "phpSniffer.standard": "PSR12",
```

[EditorConfig](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) would be also very helpful to force indentations per project and proper line endings (for PHP it's `lf`, even on Windows). Create `.editorconfig` file in your project root with these contents:

```
root = true

[*]
indent_style = space
indent_size = 4
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
```

**Comment by SharakPL** [comment]
@Enumbin just save your files with formatting enabled to at least set proper indentations and avoid useless commits like -1500/+1500 where the actual change is -1/+1. No reason to "fix " first and format later.

@smartdatasoft this package could use some config: at least `.editorconfig` and `.phpcs`.
`.stylelintrc.json` and `.eslintrc.json` would also be helpful to keep it clean.

**Comment by smartdatasoft** [comment]
@SharakPL 
Thank you for your suggestion. We are working to do. We will apply your suggestion asap.

Thank you once again.

**Pull request merged**
